kafka:
  bootstrap_servers: "kafka:29092"
  auto_offset_reset: "earliest"
schema:
  url: "http://schema-registry:8081"
postgres:
  host: "postgres"
  port: 5432
  database: "edalab"
  user: "edalab"
  password: "edalab_password"
service:
  name: "edalab"
  port: 8080
